# coding: utf-8

"""
    config-inspector

    Get the configurational status of a currently deployed product in terms of its sub     configurational items and their corresponding health

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from ska_ser_config_inspector_client.models.deployments import Deployments
from ska_ser_config_inspector_client.models.devices import Devices
from typing import Optional, Set
from typing_extensions import Self

class ChartResponse(BaseModel):
    """
    ChartResponse
    """ # noqa: E501
    chart: StrictStr
    version: StrictStr
    health: StrictStr
    deployments: Deployments
    devices: Optional[Devices]
    __properties: ClassVar[List[str]] = ["chart", "version", "health", "deployments", "devices"]

    @field_validator('health')
    def health_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['READY', 'PENDING', 'ERROR', 'UNKNOWN']):
            raise ValueError("must be one of enum values ('READY', 'PENDING', 'ERROR', 'UNKNOWN')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChartResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of deployments
        if self.deployments:
            _dict['deployments'] = self.deployments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of devices
        if self.devices:
            _dict['devices'] = self.devices.to_dict()
        # set to None if devices (nullable) is None
        # and model_fields_set contains the field
        if self.devices is None and "devices" in self.model_fields_set:
            _dict['devices'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChartResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chart": obj.get("chart"),
            "version": obj.get("version"),
            "health": obj.get("health"),
            "deployments": Deployments.from_dict(obj["deployments"]) if obj.get("deployments") is not None else None,
            "devices": Devices.from_dict(obj["devices"]) if obj.get("devices") is not None else None
        })
        return _obj


