# coding: utf-8

"""
    config-inspector

    Get the configurational status of a currently deployed product in terms of its sub     configurational items and their corresponding health

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ska_ser_config_inspector_client.api.charts_and_release_data_api import ChartsAndReleaseDataApi


class TestChartsAndReleaseDataApi(unittest.TestCase):
    """ChartsAndReleaseDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChartsAndReleaseDataApi()

    def tearDown(self) -> None:
        pass

    def test_get_release_get(self) -> None:
        """Test case for get_release_get

        Get Release
        """
        pass

    def test_get_sub_chart_chart_name_get(self) -> None:
        """Test case for get_sub_chart_chart_name_get

        Get Sub Chart
        """
        pass

    def test_search_for_sub_charts_search_charts_get(self) -> None:
        """Test case for search_for_sub_charts_search_charts_get

        Search For Sub Charts
        """
        pass


if __name__ == '__main__':
    unittest.main()
