# coding: utf-8

"""
    config-inspector

    Get the configurational status of a currently deployed product in terms of its sub     configurational items and their corresponding health

    The version of the OpenAPI document: 0.2.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ska_ser_config_inspector_client.api.control_api import ControlApi


class TestControlApi(unittest.TestCase):
    """ControlApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ControlApi()

    def tearDown(self) -> None:
        pass

    def test_ping_server_and_get_current_time_on_server_ping_get(self) -> None:
        """Test case for ping_server_and_get_current_time_on_server_ping_get

        Ping Server And Get Current Time On Server
        """
        pass


if __name__ == '__main__':
    unittest.main()
