# coding: utf-8

"""
    config-inspector

    Get the configurational status of a currently deployed product in terms of its sub     configurational items and their corresponding health

    The version of the OpenAPI document: 0.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ska_ser_config_inspector_client.models.device_response import DeviceResponse

class TestDeviceResponse(unittest.TestCase):
    """DeviceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceResponse:
        """Test DeviceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceResponse`
        """
        model = DeviceResponse()
        if include_optional:
            return DeviceResponse(
                name = '',
                deployment_status = 'Running',
                device_properties = ska_ser_config_inspector_client.models.device_properties.Device Properties(),
                device_attributes = [
                    ''
                    ],
                state = 'Unknown',
                chart = ''
            )
        else:
            return DeviceResponse(
                name = '',
                deployment_status = 'Running',
                device_properties = ska_ser_config_inspector_client.models.device_properties.Device Properties(),
                device_attributes = [
                    ''
                    ],
                chart = '',
        )
        """

    def testDeviceResponse(self):
        """Test DeviceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
